### ISSUE TITLE
`tomllib` not supported in `python<3.11`

### ISSUE THREAD

**Issue by nils-herrmann** [nils-herrmann/sprynger#51]
Fix by adding exception in import
``` py
try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    import tomli as tomllib  # Backport for older versions

```

Fix by adding as dependency for `python <3.11`
``` toml
[project]
requires-python = ">=3.9"

[project.dependencies]
tomli = {version = ">=1.2.3", markers = "python_version < '3.11'"}


```
